### ISSUE TITLE
Remove redundant namespace in front of project name

### ISSUE THREAD

**Issue by DJViking** [jenkinsci/gitlab-branch-source-plugin#129]
When selecting Owner namespace that namespace is prefixed on all repositories under the GitLab Branch
That is redundant and not necessary.
Group/ProjectA
Group/ProjectB

When standing in the GitLab Folder Group, why not ommit the `Group/` prefix?
If it is even possible, or feasible in Jenkins?

In Blue Ocean these projects are shown as
Group / Group/Project

**Comment by DJViking** [comment]
Excellent. I should have read the documentation more closely.

**Comment by robross0606** [comment]
This is not a great solution either.  The reason is that one is the full **path** while the other is the "Friendly" name.  What this means is that, if someone changes the friendly name of the project (not the git path) it will misalign and duplicate in Jenkins when scanned.

So, let's say I have a project at this path:
```
group/my-project
```
And it has a friendly name of "My Project".

I have a choice of Jenkins using "My Project", and then someone changes that later and suddenly it is "My First Project" but the path is still `group/my-project`.

Or I can use `group/my-project` and have the redundant part.

What missing is being able to use just `my-project`.
