### ISSUE TITLE
One Time Open Source Donation

### ISSUE THREAD

**Issue by ravage84** [jenkinsci/gitlab-branch-source-plugin#272]
Hello,
 
The web dev company I work for donates 50.- Swiss Francs (approx. 50 USD) to an open source developer or project chosen by our dev team each month for their efforts in the open source community.
 
https://twitter.com/ORCAServicesAG
 
We would like to donate to the GitLab Branch Source plugin for its usefulness to our team and the broader Jenkins community.
 
Since this would be a one time, 50.- CHF donation, I was hoping you could provide me some means to send you the money.
In this case, we aren't sure who to donate to.

According to [GitLab Branch Source plugin page](https://plugins.jenkins.io/gitlab-branch-source/) the maintainers of this plugin are:

- Parichay Barpanda
- Marky Jackson
- Justin Harringa
- Joseph Petersen
- Rick

The most active [contributors](https://github.com/jenkinsci/gitlab-branch-source-plugin/graphs/contributors) seem to be:
- @baymac
- @jetersen
- @LinuxSuRen
- @mifitous

If you prefer to let us donate the money to a charity, the Jenkins project in general or something else, that would be fine, too.
 
Thank you very much for your work.
 
Greetings from Basel, Switzerland
Marc

**Comment by mifitous** [comment]
Dear @ravage84 

I am so grateful to have been chosen to receive your generous donation! Indeed, I've been very active last months to fix some of the Jenkins Plugins (mainly because it seems there are plugin owners but they don't have enough time and bandwidth to support the issues and request)

For [GitLab Branch Source plugin page](https://plugins.jenkins.io/gitlab-branch-source/) it seems I'm now the main contributor, and I try to improve the code to support all different requests and issues that are raised there

If you wish to send the money, I've a [PayPal account](paypal.me/MichaelFitoussi)

But I think that most important is to promote the community contribution reward in social medias - I think if you can drop a short message with the reward prize in [LinkedIn](https://www.linkedin.com/in/mifitous/) it will encourage others to do the same

Sincerely,

@mifitous

**Comment by ravage84** [comment]
@jetersen are you OK with @mifitous receiving our one time donation?

**Comment by LinuxSuRen** [comment]
hi everyone, so happy to know you're care about this plugin. I cannot promise time on this project. Hopefully this project could keep the active status.

**Comment by mifitous** [comment]
> @jetersen are you OK with @mifitous receiving our one time donation?

;-)

**Comment by jetersen** [comment]
@ravage84 sure feel free to donate how you please :)

I am only helping review code out of interest and sometime holding back the project.
Hope someone else will step up and adopt the plugin :)
